<?php

namespace App\Http\Controllers;

use OpenApi\Annotations as OA;

/**
 * @OA\Info(title="ALODO — API du diagnostic MPME", version="1.0.0", description="Documentation générée depuis les annotations des contrôleurs. Obtenir data.token via login/register, puis utiliser Authorize. Les identifiants des exemples sont fictifs.")
 *
 * @OA\Server(url="/", description="Backend courant")
 *
 * @OA\SecurityScheme(securityScheme="bearerAuth", type="http", scheme="bearer", description="Token Laravel Sanctum, sans préfixe Bearer dans Authorize.")
 *
 * @OA\Schema(schema="Role", type="object", @OA\Property(property="id", type="integer", minimum=1, example=1), @OA\Property(property="intitule", type="string", enum={"user", "admin"}), @OA\Property(property="created_at", type="string", format="date-time", nullable=true), @OA\Property(property="updated_at", type="string", format="date-time", nullable=true), required={"id", "intitule"})
 * @OA\Schema(schema="User", type="object", @OA\Property(property="id", type="integer", minimum=1, example=1), @OA\Property(property="name", type="string"), @OA\Property(property="email", type="string", format="email"), @OA\Property(property="role_id", type="integer", minimum=1, example=1), @OA\Property(property="email_verified_at", type="string", format="date-time", nullable=true), @OA\Property(property="created_at", type="string", format="date-time", nullable=true), @OA\Property(property="updated_at", type="string", format="date-time", nullable=true), required={"id", "name", "email", "role_id"})
 * @OA\Schema(schema="AuthenticatedUser", allOf={@OA\Schema(ref="#/components/schemas/User"), @OA\Schema(type="object", @OA\Property(property="role", ref="#/components/schemas/Role"), required={"role"})})
 * @OA\Schema(schema="AuthData", type="object", @OA\Property(property="token", type="string", description="Token Sanctum à copier dans Authorize, sans le préfixe Bearer."), @OA\Property(property="user", ref="#/components/schemas/AuthenticatedUser"), required={"token", "user"})
 * @OA\Schema(schema="RegisterRequest", type="object", @OA\Property(property="name", type="string", minLength=1, maxLength=255, example="Atelier Exemple"), @OA\Property(property="email", type="string", format="email", maxLength=255, example="entreprise@example.com"), @OA\Property(property="password", type="string", minLength=8, format="password", example="ExempleMotDePasse2026!"), required={"name", "email", "password"})
 * @OA\Schema(schema="LoginRequest", type="object", @OA\Property(property="email", type="string", format="email", maxLength=255, example="entreprise@example.com"), @OA\Property(property="password", type="string", minLength=8, format="password", example="ExempleMotDePasse2026!"), required={"email", "password"})
 * @OA\Schema(schema="Error", type="object", @OA\Property(property="success", type="boolean", enum={false}), @OA\Property(property="message", type="string"), @OA\Property(property="errors", type="object", nullable=true, @OA\AdditionalProperties(type="array", @OA\Items(type="string"))), required={"message"}, description="Les erreurs Laravel peuvent ne contenir que message. Les contrôleurs peuvent ajouter success:false et errors:null.")
 * @OA\Schema(schema="ValidationError", type="object", @OA\Property(property="success", type="boolean", enum={false}), @OA\Property(property="message", type="string"), @OA\Property(property="errors", type="object", @OA\AdditionalProperties(type="array", @OA\Items(type="string"))), required={"message", "errors"}, example={"message"="The given data was invalid.", "errors"={"responses.0.valeur"={"The selected responses.0.valeur is invalid."}}})
 * @OA\Schema(schema="Option", type="object", @OA\Property(property="value", type="string", minLength=1, maxLength=100), @OA\Property(property="label", type="string", minLength=1, maxLength=255), required={"value", "label"}, additionalProperties=false)
 * @OA\Schema(schema="DomainRequest", type="object", @OA\Property(property="intitule", type="string", minLength=1, maxLength=100), @OA\Property(property="description", type="string", nullable=true), @OA\Property(property="ordre", type="integer", minimum=1, maximum=8, description="Unique parmi tous les domaines."), @OA\Property(property="is_scored", type="boolean"), required={"intitule", "ordre", "is_scored"})
 * @OA\Schema(schema="Domain", type="object", @OA\Property(property="id", type="integer", minimum=1, example=1), @OA\Property(property="intitule", type="string", minLength=1, maxLength=100), @OA\Property(property="description", type="string", nullable=true), @OA\Property(property="ordre", type="integer", minimum=1, maximum=8, description="Unique parmi tous les domaines."), @OA\Property(property="is_scored", type="boolean"), @OA\Property(property="created_at", type="string", format="date-time", nullable=true), @OA\Property(property="updated_at", type="string", format="date-time", nullable=true), required={"id", "intitule", "ordre", "is_scored"})
 * @OA\Schema(schema="QuestionRequest", oneOf={@OA\Schema(type="object", @OA\Property(property="intitule", type="string", minLength=1, maxLength=255), @OA\Property(property="domain_id", type="integer", minimum=1, example=1), @OA\Property(property="ordre", type="integer", minimum=1), @OA\Property(property="type", type="string", enum={"unique_choice", "multiple_choice"}), @OA\Property(property="options", type="array", @OA\Items(ref="#/components/schemas/Option"), minItems=2, description="Les value doivent être distinctes dans une même question."), required={"intitule", "domain_id", "ordre", "type", "options"}), @OA\Schema(type="object", @OA\Property(property="intitule", type="string", minLength=1, maxLength=255), @OA\Property(property="domain_id", type="integer", minimum=1, example=1), @OA\Property(property="ordre", type="integer", minimum=1), @OA\Property(property="type", type="string", enum={"text", "number"}), required={"intitule", "domain_id", "ordre", "type"})}, description="Options obligatoires pour les choix ; omettre options pour texte/nombre. question_code ne fait pas partie des champs validés par cet endpoint.")
 * @OA\Schema(schema="Question", type="object", @OA\Property(property="id", type="integer", minimum=1, example=1), @OA\Property(property="intitule", type="string", minLength=1, maxLength=255), @OA\Property(property="domain_id", type="integer", minimum=1, example=1), @OA\Property(property="ordre", type="integer", minimum=1), @OA\Property(property="type", type="string", enum={"unique_choice", "multiple_choice", "text", "number"}), @OA\Property(property="options", type="array", @OA\Items(ref="#/components/schemas/Option"), minItems=2, description="Les value doivent être distinctes dans une même question.", nullable=true), @OA\Property(property="question_code", type="string", nullable=true), @OA\Property(property="created_at", type="string", format="date-time", nullable=true), @OA\Property(property="updated_at", type="string", format="date-time", nullable=true), required={"id", "intitule", "domain_id", "ordre", "type"})
 * @OA\Schema(schema="QuestionnaireQuestion", type="object", @OA\Property(property="id", type="integer", minimum=1, example=1), @OA\Property(property="intitule", type="string"), @OA\Property(property="type", type="string", enum={"unique_choice", "multiple_choice", "text", "number"}), @OA\Property(property="ordre", type="integer"), @OA\Property(property="options", type="array", @OA\Items(ref="#/components/schemas/Option"), nullable=true), @OA\Property(property="valeur", oneOf={@OA\Schema(type="string", nullable=true), @OA\Schema(type="number"), @OA\Schema(type="array", @OA\Items(type="string"))}), required={"id", "intitule", "type", "ordre", "options", "valeur"})
 * @OA\Schema(schema="QuestionnaireDomain", type="object", @OA\Property(property="id", type="integer", minimum=1, example=1), @OA\Property(property="intitule", type="string"), @OA\Property(property="description", type="string", nullable=true), @OA\Property(property="ordre", type="integer"), @OA\Property(property="is_scored", type="boolean"), @OA\Property(property="questions", type="array", @OA\Items(ref="#/components/schemas/QuestionnaireQuestion")), required={"id", "intitule", "description", "ordre", "is_scored", "questions"})
 * @OA\Schema(schema="Questionnaire", type="object", @OA\Property(property="diagnostic", type="object", @OA\Property(property="id", type="integer", minimum=1, example=1), @OA\Property(property="status", type="string", enum={"baseline", "pending", "completed"}), @OA\Property(property="completed_at", type="string", nullable=true, description="Date brute du modèle Diagnostic, sans cast datetime ; null avant finalisation.", example="2026-09-14 10:00:00"), required={"id", "status", "completed_at"}), @OA\Property(property="domains", type="array", @OA\Items(ref="#/components/schemas/QuestionnaireDomain")), required={"diagnostic", "domains"})
 * @OA\Schema(schema="AnswerInput", type="object", @OA\Property(property="question_id", type="integer", minimum=1, example=1), @OA\Property(property="valeur", oneOf={@OA\Schema(type="string", minLength=1, maxLength=5000), @OA\Schema(type="number"), @OA\Schema(type="array", @OA\Items(type="string", minLength=1), minItems=1, uniqueItems=true)}, description="Dépend du type de la question en base. Choix unique : une value chaîne autorisée. Choix multiple : liste de values chaînes autorisées sans doublons. Texte : chaîne non vide, max 5000. Nombre : valeur numérique (le serveur accepte aussi une chaîne numérique). Aucune valeur booléenne pour les choix."), required={"question_id", "valeur"})
 * @OA\Schema(schema="AnswersRequest", type="object", @OA\Property(property="diagnostic_id", type="integer", minimum=1, example=1), @OA\Property(property="status", type="string", enum={"pending", "completed"}), @OA\Property(property="responses", type="array", @OA\Items(ref="#/components/schemas/AnswerInput"), minItems=1, description="Chaque question_id doit être distinct. Les réponses omises restent enregistrées."), required={"diagnostic_id", "status", "responses"})
 * @OA\Schema(schema="SavedAnswer", type="object", @OA\Property(property="id", type="integer", minimum=1, example=1), @OA\Property(property="diagnostic_id", type="integer", minimum=1, example=1), @OA\Property(property="question_id", type="integer", minimum=1, example=1), @OA\Property(property="valeur", oneOf={@OA\Schema(type="string", nullable=true), @OA\Schema(type="number"), @OA\Schema(type="array", @OA\Items(type="string"))}), @OA\Property(property="created_at", type="string", format="date-time", nullable=true), @OA\Property(property="updated_at", type="string", format="date-time", nullable=true), required={"id", "diagnostic_id", "question_id", "valeur"})
 * @OA\Schema(schema="QuestionCalculation", type="object", @OA\Property(property="question_id", type="integer", minimum=1, example=1), @OA\Property(property="question_code", type="string"), @OA\Property(property="answer", oneOf={@OA\Schema(type="string", nullable=true), @OA\Schema(type="number"), @OA\Schema(type="array", @OA\Items(type="string"))}), @OA\Property(property="points", type="integer", nullable=true, minimum=0), @OA\Property(property="max_points", type="integer", nullable=true, minimum=0), @OA\Property(property="included", type="boolean"), @OA\Property(property="exclusion_reason", type="string", nullable=true), @OA\Property(property="exclusion_label", type="string", nullable=true), required={"question_id", "question_code", "answer", "points", "max_points", "included", "exclusion_reason", "exclusion_label"})
 * @OA\Schema(schema="DomainCalculation", type="object", @OA\Property(property="domain_id", type="integer", minimum=1, example=1), @OA\Property(property="is_scored", type="boolean"), @OA\Property(property="status", type="string", enum={"not_scored", "insufficient_coverage", "evaluated"}), @OA\Property(property="score", type="number", minimum=0, maximum=100, nullable=true), @OA\Property(property="earned_points", type="integer", minimum=0), @OA\Property(property="max_points", type="integer", minimum=0), @OA\Property(property="coverage", type="object", @OA\Property(property="evaluated", type="integer", minimum=0), @OA\Property(property="total", type="integer", minimum=0), required={"evaluated", "total"}), @OA\Property(property="questions", type="object", @OA\AdditionalProperties(ref="#/components/schemas/QuestionCalculation")), required={"domain_id", "is_scored", "status", "score", "earned_points", "max_points", "coverage", "questions"})
 * @OA\Schema(schema="ScoringDetails", type="object", @OA\Property(property="scoring_version", type="string", example="1.0.0"), @OA\Property(property="status", type="string", enum={"evaluated", "partial"}), @OA\Property(property="score", type="number", minimum=0, maximum=100, nullable=true), @OA\Property(property="coverage", type="object", @OA\Property(property="evaluated_domains", type="integer", minimum=0), @OA\Property(property="scored_domains", type="integer", minimum=0), required={"evaluated_domains", "scored_domains"}), @OA\Property(property="domains", type="object", @OA\Property(property="general", ref="#/components/schemas/DomainCalculation"), @OA\Property(property="finance", ref="#/components/schemas/DomainCalculation"), @OA\Property(property="comptabilite", ref="#/components/schemas/DomainCalculation"), @OA\Property(property="commercial", ref="#/components/schemas/DomainCalculation"), required={"general", "finance", "comptabilite", "commercial"}), required={"scoring_version", "status", "score", "coverage", "domains"})
 * @OA\Schema(schema="Finding", type="object", @OA\Property(property="text", type="string", minLength=1, maxLength=1500), @OA\Property(property="question_codes", type="array", @OA\Items(type="string"), minItems=1, maxItems=12, description="Codes de questions présents dans le diagnostic analysé."), required={"text", "question_codes"})
 * @OA\Schema(schema="Weakness", type="object", @OA\Property(property="text", type="string", minLength=1, maxLength=1500), @OA\Property(property="question_codes", type="array", @OA\Items(type="string"), minItems=1, maxItems=12, description="Codes de questions présents dans le diagnostic analysé."), @OA\Property(property="kind", type="string", enum={"observed", "limitation"}), required={"text", "question_codes", "kind"})
 * @OA\Schema(schema="Recommendation", type="object", @OA\Property(property="action", type="string", minLength=1, maxLength=1500), @OA\Property(property="expected_benefit", type="string", minLength=1, maxLength=1500), @OA\Property(property="question_codes", type="array", @OA\Items(type="string"), minItems=1, maxItems=12, description="Codes de questions présents dans le diagnostic analysé."), required={"action", "expected_benefit", "question_codes"})
 * @OA\Schema(schema="Analysis", type="object", @OA\Property(property="summary", type="string", minLength=1, maxLength=3000), @OA\Property(property="strengths", type="array", @OA\Items(ref="#/components/schemas/Finding"), maxItems=5), @OA\Property(property="weaknesses", type="array", @OA\Items(ref="#/components/schemas/Weakness"), minItems=1, maxItems=5), @OA\Property(property="recommendations", type="array", @OA\Items(ref="#/components/schemas/Recommendation"), minItems=1, maxItems=3), required={"summary", "strengths", "weaknesses", "recommendations"})
 * @OA\Schema(schema="NullableAnalysis", type="object", @OA\Property(property="summary", type="string", minLength=1, maxLength=3000), @OA\Property(property="strengths", type="array", @OA\Items(ref="#/components/schemas/Finding"), maxItems=5), @OA\Property(property="weaknesses", type="array", @OA\Items(ref="#/components/schemas/Weakness"), minItems=1, maxItems=5), @OA\Property(property="recommendations", type="array", @OA\Items(ref="#/components/schemas/Recommendation"), minItems=1, maxItems=3), required={"summary", "strengths", "weaknesses", "recommendations"}, nullable=true)
 * @OA\Schema(schema="Result", type="object", @OA\Property(property="id", type="integer", minimum=1, example=1), @OA\Property(property="diagnostic_id", type="integer", minimum=1, example=1), @OA\Property(property="score", type="string", nullable=true, pattern="^\d+\.\d{2}$", example="66.67", description="Décimal sérialisé en chaîne. null signifie non calculable, pas zéro."), @OA\Property(property="scoring_version", type="string", nullable=true), @OA\Property(property="scoring_details", type="object", @OA\Property(property="scoring_version", type="string", example="1.0.0"), @OA\Property(property="status", type="string", enum={"evaluated", "partial"}), @OA\Property(property="score", type="number", minimum=0, maximum=100, nullable=true), @OA\Property(property="coverage", type="object", @OA\Property(property="evaluated_domains", type="integer", minimum=0), @OA\Property(property="scored_domains", type="integer", minimum=0), required={"evaluated_domains", "scored_domains"}), @OA\Property(property="domains", type="object", @OA\Property(property="general", ref="#/components/schemas/DomainCalculation"), @OA\Property(property="finance", ref="#/components/schemas/DomainCalculation"), @OA\Property(property="comptabilite", ref="#/components/schemas/DomainCalculation"), @OA\Property(property="commercial", ref="#/components/schemas/DomainCalculation"), required={"general", "finance", "comptabilite", "commercial"}), required={"scoring_version", "status", "score", "coverage", "domains"}, nullable=true), @OA\Property(property="analysis", ref="#/components/schemas/NullableAnalysis"), @OA\Property(property="analysis_status", type="string", enum={"pending", "processing", "completed", "failed"}), @OA\Property(property="analysis_error", type="string", nullable=true), @OA\Property(property="analysis_provider", type="string", nullable=true, example="gemini"), @OA\Property(property="analysis_model", type="string", nullable=true), @OA\Property(property="prompt_version", type="string", nullable=true), @OA\Property(property="analyzed_at", type="string", format="date-time", nullable=true), @OA\Property(property="created_at", type="string", format="date-time", nullable=true), @OA\Property(property="updated_at", type="string", format="date-time", nullable=true), required={"id", "diagnostic_id", "score", "analysis", "analysis_status"}, description="Résultat persisté. interpretation_input est masqué. Les anciennes lignes peuvent ne pas avoir de détail de scoring ; la relance les refuse alors avec 409.")
 * @OA\Schema(schema="NullableResult", type="object", @OA\Property(property="id", type="integer", minimum=1, example=1), @OA\Property(property="diagnostic_id", type="integer", minimum=1, example=1), @OA\Property(property="score", type="string", nullable=true, pattern="^\d+\.\d{2}$", example="66.67", description="Décimal sérialisé en chaîne. null signifie non calculable, pas zéro."), @OA\Property(property="scoring_version", type="string", nullable=true), @OA\Property(property="scoring_details", type="object", @OA\Property(property="scoring_version", type="string", example="1.0.0"), @OA\Property(property="status", type="string", enum={"evaluated", "partial"}), @OA\Property(property="score", type="number", minimum=0, maximum=100, nullable=true), @OA\Property(property="coverage", type="object", @OA\Property(property="evaluated_domains", type="integer", minimum=0), @OA\Property(property="scored_domains", type="integer", minimum=0), required={"evaluated_domains", "scored_domains"}), @OA\Property(property="domains", type="object", @OA\Property(property="general", ref="#/components/schemas/DomainCalculation"), @OA\Property(property="finance", ref="#/components/schemas/DomainCalculation"), @OA\Property(property="comptabilite", ref="#/components/schemas/DomainCalculation"), @OA\Property(property="commercial", ref="#/components/schemas/DomainCalculation"), required={"general", "finance", "comptabilite", "commercial"}), required={"scoring_version", "status", "score", "coverage", "domains"}, nullable=true), @OA\Property(property="analysis", ref="#/components/schemas/NullableAnalysis"), @OA\Property(property="analysis_status", type="string", enum={"pending", "processing", "completed", "failed"}), @OA\Property(property="analysis_error", type="string", nullable=true), @OA\Property(property="analysis_provider", type="string", nullable=true, example="gemini"), @OA\Property(property="analysis_model", type="string", nullable=true), @OA\Property(property="prompt_version", type="string", nullable=true), @OA\Property(property="analyzed_at", type="string", format="date-time", nullable=true), @OA\Property(property="created_at", type="string", format="date-time", nullable=true), @OA\Property(property="updated_at", type="string", format="date-time", nullable=true), required={"id", "diagnostic_id", "score", "analysis", "analysis_status"}, description="Résultat persisté. interpretation_input est masqué. Les anciennes lignes peuvent ne pas avoir de détail de scoring ; la relance les refuse alors avec 409.", nullable=true)
 * @OA\Schema(schema="AnswersData", type="object", @OA\Property(property="result", ref="#/components/schemas/NullableResult"), @OA\Property(property="responses", type="array", @OA\Items(ref="#/components/schemas/SavedAnswer")), @OA\Property(property="newStatus", type="string", enum={"pending", "completed"}), @OA\Property(property="completed_at", type="string", nullable=true, description="Date de finalisation ; format brut du modèle, non garanti ISO 8601 dans cette réponse."), required={"result", "responses", "newStatus", "completed_at"})
 *
 * @OA\Response(response="Unauthorized", description="401 : token absent/invalide ou identifiants de connexion incorrects.", @OA\JsonContent(ref="#/components/schemas/Error"))
 * @OA\Response(response="Forbidden", description="403 : rôle non autorisé.", @OA\JsonContent(ref="#/components/schemas/Error"))
 * @OA\Response(response="NotFound", description="404 : ressource absente, diagnostic inaccessible ou rôle non configuré.", @OA\JsonContent(ref="#/components/schemas/Error"))
 * @OA\Response(response="Validation", description="422 : données invalides. Les clés responses.{index}.valeur concernent la soumission ; answers.{question_id} concerne la complétude finale. diagnostic_id peut signaler un diagnostic déjà terminé.", @OA\JsonContent(ref="#/components/schemas/ValidationError"))
 * @OA\Response(response="Conflict", description="409 : seule une interprétation failed avec ses données de calcul et son instantané peut être relancée.", @OA\JsonContent(ref="#/components/schemas/Error"))
 * @OA\Response(response="ServerError", description="500 : erreur serveur, notamment incohérence entre questions et barème lors de la finalisation. La transaction de cette soumission est annulée.", @OA\JsonContent(ref="#/components/schemas/Error"))
 * @OA\Response(response="BadRequest", description="400 : un domaine de même intitulé existe déjà.", @OA\JsonContent(ref="#/components/schemas/Error"))
 */
abstract class Controller
{
    //
}
